# -*- coding: utf-8 -*-
"""Statistische_Modellierung_600279.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BeU2A6DJkziTF1OmKyFf1WyKUn5aStA2
"""

# =========================================================================
# KAPITEL 4: STATISTISCHE MODELLIERUNG — Sipan Cheikhi (600279)
# Seminararbeit: Faktoren der Hilfsfristen bei der Berliner Feuerwehr
# =========================================================================

import pandas as pd
import statsmodels.formula.api as smf

def compute_response_time_regression(csv_path: str) -> None:
    """
    Führt eine Multiple Lineare Regression zur Identifikation und Quantifizierung
    der Einflussfaktoren auf die Hilfsfristen der Berliner Feuerwehr durch.
    """

    # Einlesen des bereinigten Master-Datensatzes
    try:
        df = pd.read_csv(csv_path, low_memory=False)
        print(f"Datensatz erfolgreich geladen. Ursprüngliche Zeilen: {len(df):,}")
    except FileNotFoundError:
        print(f"Fehler: Die Datei {csv_path} wurde nicht gefunden.")
        return

    # Datenvorbereitung und Filterung (Complete-Case-Analysis)
    # Wir filtern den Datensatz auf die für das Modell relevanten Spalten
    # und entfernen Zeilen mit fehlenden Werten (NaNs).
    relevante_variablen = [
        'response_time',
        'dispatchcode_criticality',
        'Density',
        'Distance_to_Station_m'
    ]

    df_model = df[relevante_variablen].dropna()
    print(f"Zeilen nach Entfernung fehlender Werte (n): {len(df_model):,}")

    # Spezifikation der Modellgleichung
    # Die kategoriale Variable (Dringlichkeit) wird mit C() umschlossen,
    # damit statsmodels automatisch Dummy-Variablen erstellt.
    formula = (
        'response_time ~ C(dispatchcode_criticality) + '
        'Density + '
        'Distance_to_Station_m'
    )

    # Modellanpassung mittels Ordinary Least Squares (OLS)
    model = smf.ols(formula=formula, data=df_model).fit()

    # Ausgabe der Regressionstabelle
    print("\n--- Ergebnisse der Multiplen Linearen Regression ---")
    print(model.summary())

if __name__ == '__main__':
    # Aufruf der Funktion mit der finalen CSV-Datei
    compute_response_time_regression('incidents_2023_cleaned_TEAM.csv')